services:
  - type: web
    name: baron-c2
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: baron-db
          property: connectionString
      - key: BARON_SECRET
        generateValue: true
      - key: PORT
        value: 8080
      - key: GO_ENV
        value: production

databases:
  - name: baron-db
    plan: free
